### ISSUE TITLE
[BUG] On library Update, previous chapters get deleted

### ISSUE THREAD

**Issue by Altair2169** [Flameish/Novel-Grabber#134]
**Describe the bug**

whenever the library detects a new update, the chapters get downloaded but it deletes the older chapters

**Expected behavior**

The downloaded chapters should be added to the old ones

**Platform**

Windows 10 Java 14

**Logs**

```
[2021-03-18T08:46:09] Chapter container not found.
[2021-03-18T08:47:53] Could not save image: Fantastic-Tree.jpg
[2021-03-18T08:48:10] Could not save image: tari-tari-03-3.jpg
[2021-03-18T08:48:14] java.io.IOException: Server returned HTTP response code: 403 for URL: http://data.whicdn.com/images/60505131/large.jpg
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:48:14] Could not save image: large.jpg
[2021-03-18T08:48:29] Could not save image: monolith_by_reneaigner-d4ojqar.jpg
[2021-03-18T08:48:37] Could not save image: blood_rain_by_kush_solitary.jpg
[2021-03-18T08:49:13] Could not save image: MNIiHai.jpg
[2021-03-18T08:49:16] Could not save image: the_smile_of_a_dying_old_man_by_witchofwest-d41ug5c.jpg
[2021-03-18T08:49:18] java.net.UnknownHostException: www.hotupub.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1256)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1595)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:49:18] Could not save image: 1157430vg7tob4r7y5vhnp.gif
[2021-03-18T08:49:36] Could not save image: turtle_by_randis-d7cjeyp.jpg
[2021-03-18T08:49:38] java.io.IOException: Server returned HTTP response code: 403 for URL: http://cdn.ipernity.com/200/06/04/36620604.13d191e4.640.jpg?r2
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:49:38] Could not save image: 36620604.13d191e4.640.jpg
[2021-03-18T08:49:44] java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1618)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:49:44] Could not save image: cliff-019.jpg
[2021-03-18T08:49:49] java.io.FileNotFoundException: http://www.autoszelvedocsere.com/thumbnail/e/entrance-to-mythical-garden-outdoor-ideas-and-beautification-pint-2.jpeg
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1923)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:49:49] Could not save image: entrance-to-mythical-garden-outdoor-ideas-and-beautification-pint-2.jpeg
[2021-03-18T08:49:55] java.io.IOException: Server returned HTTP response code: 503 for URL: https://www.organicfacts.net/wp-content/uploads/ginsengteainfographic.jpg
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1927)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:49:55] Could not save image: ginsengteainfographic.jpg
[2021-03-18T08:49:58] Could not save image: flying_tree_1_2560x1600.jpg
[2021-03-18T08:50:25] Could not save image: HL203_EAGLE_&_DRAGON.jpg
[2021-03-18T08:50:44] java.io.FileNotFoundException: https://media.licdn.com/mpr/mpr/p/8/005/094/17e/0d91eb8.jpg
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1923)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:50:44] Could not save image: 0d91eb8.jpg
[2021-03-18T08:51:10] java.net.UnknownHostException: www.hotupub.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1256)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1595)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:51:10] Could not save image: 194131nkvv8ok20pq08t64.gif
[2021-03-18T08:51:35] java.net.UnknownHostException: www.hotupub.com
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1256)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1595)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at grabber.GrabberUtils.getImage(GrabberUtils.java:46)
	at grabber.Chapter.getImages(Chapter.java:98)
	at grabber.Chapter.saveChapter(Chapter.java:49)
	at grabber.Novel.downloadChapters(Novel.java:110)
	at gui.GUI.lambda$null$2(GUI.java:309)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

[2021-03-18T08:51:35] Could not save image: 1941363goigx4cg4jpjx6i.gif
[2021-03-18T08:51:44] Could not save image: PEOPLE_DIE_IF_THEY_ARE_KILLED.jpg
[2021-03-18T09:20:17] Failed to download: Chapter 219 : Grand Dao Saint (1)
[2021-03-18T09:41:14] Could not read old book file.
[2021-03-18T09:42:28] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-18T13:34:33] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-19T16:46:43] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-19T16:46:53] Could not read old book file.
[2021-03-19T16:46:56] Could not read old book file.
[2021-03-19T16:47:16] Could not read old book file.
[2021-03-19T17:24:26] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-20T16:42:54] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-20T16:43:05] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-20T16:43:05] Could not read old book file.
[2021-03-20T16:43:41] Could not read old book file.
[2021-03-21T11:27:18] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-21T11:27:41] Could not read old book file.
[2021-03-21T11:29:59] Could not read old book file.
[2021-03-22T11:58:00] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-03-22T11:58:10] Chapter container not found.
[2021-03-22T11:58:11] Failed to download: Chapter 2079: Interception

```

**Additional context**

**Comment by Flameish** [comment]
Released a new update which includes the moving of the file if it was just downloaded. Maybe try again with that.
Also from the log you can see that it can't read/find the old file so it creates a new one with just the new chapters.

**Comment by Altair2169** [comment]
Thanks for the fix, I'll try it out

**Comment by Altair2169** [comment]
I just tried it and yea it's working fine. thank you
