### ISSUE TITLE
[BUG]Can't download a whole novel from lightnovelstranslations

### ISSUE THREAD

**Issue by SqueezedByte** [Flameish/Novel-Grabber#164]
If I try to download all chapter of this web novel it stop at 95
https://lightnovelstranslations.com/i-woke-up-piloting-the-strongest-starship-so-i-became-a-space-mercenary/
**Describe the bug**

If I try to download this https://lightnovelstranslations.com/i-woke-up-piloting-the-strongest-starship-so-i-became-a-space-mercenary/ it stop at chapter 95. 
It not generate epub file and don't go on.

**Steps to reproduce**

1. Automatic mode
2. Novel URL : https://lightnovelstranslations.com/i-woke-up-piloting-the-strongest-starship-so-i-became-a-space-mercenary/
3. Click "Check aviability of novel
4. Click "All"
5. Click Grab Chapter

**Expected behavior**

The download of all chapter

**Screenshots**

![image](https://user-images.githubusercontent.com/33869313/114352595-5765e180-9b6c-11eb-9f80-4a0bc51fbef5.png)

**Platform**

Windows 10 Pro
Java 8/281

**Logs**
[INFO]Saved chapter: Chapter 95
Exception in thread "pool-3-thread-1" java.lang.IllegalArgumentException: Must supply a valid URL
        at org.jsoup.helper.Validate.notEmpty(Validate.java:102)
        at org.jsoup.helper.HttpConnection.url(HttpConnection.java:127)
        at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:70)
        at org.jsoup.Jsoup.connect(Jsoup.java:73)
        at grabber.sources.lightnovelstranslations_com.getChapterContent(lightnovelstranslations_com.java:66)
        at grabber.Chapter.saveChapter(Chapter.java:38)
        at grabber.Novel.downloadChapters(Novel.java:117)
        at gui.GUI.lambda$null$2(GUI.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Additional context**

**Comment by Flameish** [comment]
Thanks for the report!
Seems like there are empty links on the table of content page, which you can see on the "Show all" view of Chapter list view:
![image](https://i.imgur.com/ntQRu5U.png)
![image2](https://i.imgur.com/1L4VLvc.png)

Fixed now.
