### ISSUE TITLE
[BUG] novelupdate not working with headless browser

### ISSUE THREAD

**Issue by sharak214** [Flameish/Novel-Grabber#166]
**Describe the bug**

**Steps to reproduce**

1. [https://www.novelupdates.com/series/the-strongest-dull-princes-secret-battle-for-the-throne/](https://www.novelupdates.com/series/the-strongest-dull-princes-secret-battle-for-the-throne/)
2. select check for new releases or download new chapter
3. 
4. 

**Expected behavior**
expect headless browser to check if any new chapters are avaible

**Screenshots**

**Platform**

System info: host:  os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: **'1.8.0_211'**

**Logs**
[INFO]Starting browser...
Exception in thread "pool-2-thread-1" org.openqa.selenium.NoSuchElementException: Returned node (null) was not a DOM element
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
 os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_211'
Driver info: driver.version: HtmlUnitDriver
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElementByCssSelector(HtmlUnitDriver.java:1320)
        at org.openqa.selenium.By$ByCssSelector.findElement(By.java:431)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver$4.call(HtmlUnitDriver.java:2046)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver$4.call(HtmlUnitDriver.java:2042)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.implicitlyWaitFor(HtmlUnitDriver.java:1677)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:2042)
        at org.openqa.selenium.htmlunit.HtmlUnitDriver.findElement(HtmlUnitDriver.java:814)
        at grabber.sources.novelupdates_com.getChapterList(novelupdates_com.java:61)
        at grabber.Novel.check(Novel.java:80)
        at library.Library.checkNovel(Library.java:277)
        at gui.libraryNovelSettings.lambda$null$7(libraryNovelSettings.java:112)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Additional context**
have used both firefox and chrome to check and they open a browser page to check novelupdates chapter list. download new chapter also open the relavent url for the  chapters and saves them

**Comment by Flameish** [comment]
I'm not sure why the headless one (HtmlUnit) doesn't work but the others do, they use the same execution/navigation code. It has probably something to do with the anti bot measures implemented by NovelUpdates/Cloudflare. I'm getting a captcha check even with the regular graphical browsers nowadays which break NU grabbing either way.

**Comment by Flameish** [comment]
Closed in favor of #135
