### ISSUE TITLE
[BUG]NG-Launcher works badly in headless environment

### ISSUE THREAD

**Issue by AlekId** [Flameish/Novel-Grabber#169]
Android, armhp, Debian Bullseye via chroot/Linux Deploy
OpenJdk via
apt install default-jre-headless 
Gui is not supported anyway, and headless package takes less space
i tried:
u1@localhost:~/Novel-Grabber$ java -jar NG-Launcher.jar -gui /none 
got 
_java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/sun.java2d.HeadlessGraphicsEnvironment.getDefaultScreenDevice(HeadlessGraphicsEnvironment.java:58)
	at com.formdev.flatlaf.LinuxFontPolicy.isSystemScaling(LinuxFontPolicy.java:268)
	at com.formdev.flatlaf.LinuxFontPolicy.getGnomeFontScale(LinuxFontPolicy.java:109)
	at com.formdev.flatlaf.LinuxFontPolicy.getGnomeFont(LinuxFontPolicy.java:85)
	at com.formdev.flatlaf.LinuxFontPolicy.getFont(LinuxFontPolicy.java:42)
	at com.formdev.flatlaf.FlatLaf.initFonts(FlatLaf.java:466)
	at com.formdev.flatlaf.FlatLaf.getDefaults(FlatLaf.java:382)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:587)
	at launcher.init.lambda$startSplash$0(init.java:35)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[INFO] Fetching manifest...
[INFO] Everything up-to-date.
[INFO] Starting Novel-Grabber_...

Didnt even realize this somehow worked
tried 
java -jar NG-Launcher.jar -gui /none -help
didn't got help, only similar trace complaining about lack of X11. Stupid
Then, I tried to write bug report, and so discovered that i might need to launch jar from bin folder
tried to launch that jar and finaly got help output, along with cryptic
[ERROR]No settings file found.
[ERROR]Could not establish connection to SMTP Server. Check email settings and restart.
Wtf? email settings? Settings file missing, just recreate, and why this is error?
and finally, tried to download something with -link (why i need to specify this, url should be default param, no?)
It even worked , albeit book start with toc, and not cover, which weird to
All in all , lightnovel crawler is so much better, with zero assumption friendly pseudo gui, ability to find novel by name (killer feature!), and so much more!

**Comment by Flameish** [comment]
NG-Launcher is just the updater, the jar which you need to use for cli is inside the bin folder like you found out. I haven't actually tried to use the updater headless, I will take a look at that. I'm just not quite sure what you expected when you tried to start the Graphical User Interface (`-gui`) on a headless machine. 
`-gui` or no parameters (`none`) does the same thing, starts the "default" program (`java -jar Novel-Grabber.jar`).

You have to specify -link because that just how it was first created by me, on the other hand you can mix up the order of parameters  because of it. Eg.: `java -jar Novel-Grabber.jar -chapters 12 20 -link https:whatever.com/novel/ -getImages`

The `[ERROR]No settings file found.` pops up because: there is no settings file on first boot up, who would have thunk? You could debate if it's an error or more of an info in this case but frankly, it's not important enough to write an first-boot check for it.

NG supports notifications / automatic download of new chapters and sending those to an email address. The error text is the same for not using that feature (no saved connection data found) and failed SMTP server connection test. This could need some better distinction.  

I feel like not having the cover as a first page is a question of taste, I personally like it that way since I can see the cover any time I which via the program I use to read the ePub on anyway.

**Comment by Flameish** [comment]
Added a headless check on start up to the launcher.
