### ISSUE TITLE
No Sources

### ISSUE THREAD

**Issue by JDcarmelo** [Flameish/Novel-Grabber#170]
No sources and I can't login my webnovel account so i can only download free chapters
![image](https://user-images.githubusercontent.com/57732601/114882413-831bec80-9e36-11eb-8787-0d05d739b8f5.png)

**Comment by Flameish** [comment]
Does any normal download work? Can you check if `/Novel-Grabber/bin/sources/grabber/sources` is empty?

**Comment by JDcarmelo** [comment]
The sources is not empty in the folder
![image](https://user-images.githubusercontent.com/57732601/114953785-bb99e580-9e8b-11eb-8acb-b1af90164a42.png)
and I can download normally but I can't login my webnovel to download my unlocked chapters
![image](https://user-images.githubusercontent.com/57732601/114953868-f3a12880-9e8b-11eb-967f-98e2ded635f5.png)

I also tried using the Novel-Grabber but it's the same

**Comment by Flameish** [comment]
And there is nothing in the console log? I'm not quite sure what the cause here is, since grabbing and building the sources list uses the same function.

**Comment by JDcarmelo** [comment]
[2021-04-15T21:56:34] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-04-15T21:56:36] java.lang.ClassNotFoundException: grabber.sources.3.8.1 - webnovel_com
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at grabber.GrabberUtils.getSources(GrabberUtils.java:223)
	at gui.GUI.createUIComponents(GUI.java:1838)
	at gui.GUI.$$$setupUI$$$(GUI.java)
	at gui.GUI.<init>(GUI.java:47)
	at system.init.lambda$startGUI$0(init.java:101)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[2021-04-15T21:56:44] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-04-15T21:56:46] java.lang.ClassNotFoundException: grabber.sources.3.8.1 - webnovel_com
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at grabber.GrabberUtils.getSources(GrabberUtils.java:223)
	at gui.GUI.createUIComponents(GUI.java:1838)
	at gui.GUI.$$$setupUI$$$(GUI.java)
	at gui.GUI.<init>(GUI.java:47)
	at system.init.lambda$startGUI$0(init.java:101)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[2021-04-15T22:19:15] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-04-15T22:19:17] java.lang.ClassNotFoundException: grabber.sources.3.8.1 - webnovel_com
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at grabber.GrabberUtils.getSources(GrabberUtils.java:223)
	at gui.GUI.createUIComponents(GUI.java:1843)
	at gui.GUI.$$$setupUI$$$(GUI.java)
	at gui.GUI.<init>(GUI.java:47)
	at system.init.lambda$startGUI$0(init.java:101)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[2021-04-15T22:26:04] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-04-15T22:26:06] java.lang.ClassNotFoundException: grabber.sources.3.8.1 - webnovel_com
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at grabber.GrabberUtils.getSources(GrabberUtils.java:223)
	at gui.GUI.createUIComponents(GUI.java:1838)
	at gui.GUI.$$$setupUI$$$(GUI.java)
	at gui.GUI.<init>(GUI.java:47)
	at system.init.lambda$startGUI$0(init.java:101)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

[2021-04-16T08:12:44] Could not establish connection to SMTP Server. Check email settings and restart.
[2021-04-16T08:12:45] java.lang.ClassNotFoundException: grabber.sources.3.8.1 - webnovel_com
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:433)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at grabber.GrabberUtils.getSources(GrabberUtils.java:223)
	at gui.GUI.createUIComponents(GUI.java:1843)
	at gui.GUI.$$$setupUI$$$(GUI.java)
	at gui.GUI.<init>(GUI.java:47)
	at system.init.lambda$startGUI$0(init.java:101)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

this is all what i found in the log.txt

**Comment by JDcarmelo** [comment]
I made it work again i just deleted the source folder, downloaded stable version and update the grabber using NG-Launcher with administrator
