### ISSUE TITLE
[BUG] Error when downloading novel

### ISSUE THREAD

**Issue by jsanchezflores** [Flameish/Novel-Grabber#171]
**Describe the bug**

This shows up in the log when attempting to download this specific novel from foxaholic.
Other novels that I tried work fine.
```
[2021-04-16T01:40:07] java.lang.NullPointerException
	at grabber.sources.foxaholic_com.getMetadata(foxaholic_com.java:92)
	at grabber.Novel.check(Novel.java:81)
	at gui.GUI.lambda$null$0(GUI.java:230)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Steps to reproduce**

1. Download this [Novel](https://foxaholic.com/novel/a-neets-guide-to-the-parallel-world-healer-the-strongest-cheat/) using Novel-Grabber

**Expected behavior**

Novel-Grabber should be able to download this novel.

**Comment by Flameish** [comment]
Seems like the author was not set for that novel which is why it crashed there. I've updated the metadata selectors and made them more robust. Should be fixed now.
