### ISSUE TITLE
[BUG] Manually added chapters not outputting when in epub format

### ISSUE THREAD

**Issue by krispykiq** [Flameish/Novel-Grabber#177]
**Describe the bug**
I used the manual download and tried to download using it. It downloads but stops at "Download finished." and doesn't continue to output an epub file. 

**Steps to reproduce**
1. Use "https://experimentaltranslations.com/grimoire-master-of-an-everchanging-world/" in the manual download
2. Check get images, display chapter title, use headless browser and auto detect
3. Click Grab chapters

**Expected behavior**
Download and output an epub file

**Platform**
Windows 10 pro

**Logs**
```
[ERROR]Could not establish connection to SMTP Server. Check email settings and restart.

[INFO]Saved image: cb6d6630a6996e17710274c46c559d09.png
[INFO]Saved chapter: Prologue
[INFO]Saved image: .png
[INFO]Saved chapter: Section 1: Outside the Window
[INFO]Download finished.
Exception in thread "pool-2-thread-1" java.lang.IllegalArgumentException: formatName == null!
        at java.desktop/javax.imageio.ImageIO.getImageWriters(ImageIO.java:1166)
        at java.desktop/javax.imageio.ImageIO.getWriter(ImageIO.java:1609)
        at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1594)
        at grabber.formats.EPUB.addImages(EPUB.java:101)
        at grabber.formats.EPUB.write(EPUB.java:72)
        at grabber.Novel.output(Novel.java:271)
        at gui.GUI.lambda$null$13(GUI.java:544)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Additional context**
I recreated this by using the txt and pdf format and it worked. So it's just the epub that has the problem. I also tried this with other random novels and they also didn't work.

**Comment by Flameish** [comment]
Thanks for the report!
For some reason there is an image without a filename in the chapter,
> [INFO]Saved image: .png

which crashed the image import during the ePub creation.
> at grabber.formats.EPUB.addImages(EPUB.java:101)

On the website:
![2021-04-22_21-22](https://user-images.githubusercontent.com/47372220/115773739-f1216000-a3b0-11eb-877b-caeefcc191a2.png)


Will be fixed in next update.

Also I don't think headless grabbing is required on that website.

**Comment by Flameish** [comment]
Update is live.
