### ISSUE TITLE
[BUG] Wuxiaworld.site

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#183]
**Describe the bug**
 When someone attempts to download novels on the bot from 
 `wuxiaworld.site `  they would get this error  

`java.net.SocketTimeoutException: Read timed out`

**This is the full log:**

```
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.access$300(Unknown Source)
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(Unknown Source)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

**Steps to reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Platform**

**Logs**

**Additional context**

**Comment by Flameish** [comment]
Does this happen right at the start when the grabber is "checking" or midway during the download (eg. chapter 50). It works fine for me, I only tried 10 chapters through, so I would suggest trying again later or use a longer wait time since `Read time out` means that the server was too slow to provide an answer.

**Comment by damare01** [comment]
somtimes it happens right away somtimes midway, what if the person is a VIP?

**Comment by Flameish** [comment]
It's a server (wuxiaworld.site) issue. Being a vip won't matter at all. Their server is too slow and can't keep up. I'll take a look why it stop grabbing through, normally it should skip those and retry them at the end.

**Comment by damare01** [comment]
thank you very much!

**Comment by damare01** [comment]
what happens if a person download a manga using a telegram bot?

**Comment by Flameish** [comment]
Try it out. It might work, if you have images download enabled. I'm just not sure which host also have manga with matching page selectors.

**Comment by damare01** [comment]
It is working now so I will close this issue and thank you!
