### ISSUE TITLE
[BUG] java.net.ConnectException: Failed to connect to api.telegram.org/149.154.167.220:443

### ISSUE THREAD

**Issue by damare01** [Flameish/Novel-Grabber#192]
**Describe the bug**
 The bot will reply this sometimes while downloading novels, how do you fix/avoid it?

**Screenshots**

**Platform**
 telegram bot

**Logs**

```
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
        ... 27 more

```

**Comment by Flameish** [comment]
Sometimes the connection to Telegram cuts off for a moment, it should re-connect automatically or you can try yo restart the bot.
