### ISSUE TITLE
[BUG] Quotev not downloading properly

### ISSUE THREAD

**Issue by redrice27** [Flameish/Novel-Grabber#194]
**Describe the bug**
Can't retrieve the novel URL from quotev.com. The message popped up as follows:
[ERROR]Something went wrong, see log for more information. 

It was able to download on 5/16,but it doesn't work now.

**Platform**
Windows,Java8

**Logs**
        java.lang.NullPointerException
	at grabber.sources.quotev_com.getMetadata(quotev_com.java:80)
	at grabber.Novel.check(Novel.java:85)
	at gui.GUI.lambda$null$0(GUI.java:260)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by redrice27** [comment]
Thank you very much indeed!
