### ISSUE TITLE
[BUG] Stops grabbing novels in the middle

### ISSUE THREAD

**Issue by Altair2169** [Flameish/Novel-Grabber#248]
**Describe the bug**

Trying to scrape a novel and it stops grabbing the chapters right in the middle without any errors or anything
Here's the site and the specific novel link
[https://www.wuxiaworld.co/Gourmet-of-Another-World/](link)
**Screenshots**

![Screenshot_62](https://user-images.githubusercontent.com/80315381/125036098-4156b700-e0b0-11eb-8f8f-3ecea75f9961.png)

**Platform**

Win 10  JDK 14

**Logs**

```



[2021-07-09T11:22:27] Chapter container not found.


```

EDIT: Removed redundant logs

**Comment by Flameish** [comment]
1466 is apparently the last chapter. Check out [1467](https://www.wuxiaworld.co/Gourmet-of-Another-World/2811169.html). Nevertheless I'm not sure why it stops there (it should still grab those place holder chapters). Please post just the relevant log section next time. It just full of Boxnovel https/ssl errors.

**Comment by Altair2169** [comment]
Will do but these are the logs from when I tried to scrape the novel. I though it would be useful to have the logs from the starting of the scraping

**Comment by Flameish** [comment]
These log are actually generated by the library, you can see that on the stack trace:

`at grabber.sources.boxnovel_org.getChapterList(boxnovel_org.java:50)`
`at grabber.Novel.check(Novel.java:80)`
`at library.Library.run(Library.java:206)`

It's not happy with boxnovel's ssl certificate I think, but this is a different issue.

**Comment by Altair2169** [comment]
> These log are actually generated by the library, you can see that on the stack trace:
> 
> `at grabber.sources.boxnovel_org.getChapterList(boxnovel_org.java:50)`
> `at grabber.Novel.check(Novel.java:80)`
> `at library.Library.run(Library.java:206)`
> 
> It's not happy with boxnovel's ssl certificate I think, but this is a different issue.

Ah yes I just saw it now and yes boxnovel's security cert does have problems. I'll filter these out in the future

**Comment by Altair2169** [comment]
it happened with lightnovelpub too, here's the <a href="https://www.lightnovelpub.com/novel/tempest-of-the-stellar-war-23061410">linl</a>

**Comment by Flameish** [comment]
Works fine for me. Can't say much without the logs. Maybe a running memory issue? That shouldn't happen with just text that quickly through.

**Comment by Flameish** [comment]
Closing due to inactivity
