### ISSUE TITLE
Issue grabbing website after accident

### ISSUE THREAD

**Issue by Killo1988** [Flameish/Novel-Grabber#270]
Accidentally ran java under windows32 instead of user file location it ran again and now even after going through and removing all files I could find to do a fresh install it still gives me issues.
[log.txt](https://github.com/Flameish/Novel-Grabber/files/6988245/log.txt)
[2021-08-15T08:54:58] No settings file found.
[2021-08-15T08:54:58] No library file found.
[2021-08-15T08:55:36] java.lang.IllegalArgumentException: Must supply a valid URL
	at org.jsoup.helper.Validate.notEmpty(Validate.java:102)
	at org.jsoup.helper.HttpConnection.url(HttpConnection.java:127)
	at org.jsoup.helper.HttpConnection.connect(HttpConnection.java:70)
	at org.jsoup.Jsoup.connect(Jsoup.java:73)
	at grabber.sources.novelfull_com.getChapterList(novelfull_com.java:57)
	at grabber.Novel.check(Novel.java:80)
	at gui.GUI.lambda$null$0(GUI.java:270)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Flameish** [comment]
That's a very weird issue, it seems to crash at a basic string null check (I take it you entered a url). 

All config files are inside the Novel-Grabber folder so that's all you need to look for to delete config wise. 

I really don't know what's going on, maybe try starting it from the terminal to get some more information.
If you are on Windows go inside the Novel-Grabber/bin folder and shift-right click anywhere inside, then select 'open Powershell' from the context menu. Use `java -jar Novel-Grabber.jar -link http://someNovelLink -chapters 1 1` to test it.

**Comment by Killo1988** [comment]
Looks possibly fixed? I went into library and clicked through the download
new chapters and after that it now accepts the novel url no problem.

**Comment by Flameish** [comment]
That's good to hear! The error came because of empty novel link, so make sure they are all ok.

**Comment by Killo1988** [comment]
Going through each one in library to test them all.

**Comment by Killo1988** [comment]
Don't know exactly how i fixed it but its working now
