### ISSUE TITLE
Comrademao website support not working

### ISSUE THREAD

**Issue by croooked01** [Flameish/Novel-Grabber#28]
When URL of the novel is provided in the Novel URL option and then "check availability of novel" It doesn't show the info. and gets stuck at:
[INFO]Fetching novel info...
I have tried it with both with and without headerless browser option and am using the latest 2.4.4 version.I have tried URL of several other supported sites but they work fine and show the info.of the novel after clicking "check availability of novel" but when I do this with Comrademao novels it just shows the black Loading spiral continuously even after a long time where the info. of the novel is supposed to appear.

**Comment by Flameish** [comment]
Can you paste the error log? Start it with "java -jar Novel-Grabber.jar" in cmd/powershell

**Comment by croooked01** [comment]
Here you go:
PS C:\Users\Surbhit> java -jar Novel-Grabber.jar
Fetching latest selector JSON from GitHub...
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=503, URL=https://comrademao.com/novel/rebirth-of-the-devouring-emperor/
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
        at grabber.HostSettings.getChapterList(HostSettings.java:141)
        at grabber.Novel.getChapterList(Novel.java:71)
        at gui.GUI.lambda$null$0(GUI.java:156)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
        at grabber.Metadata.getTitle(Metadata.java:33)
        at grabber.Novel.getMetadata(Novel.java:105)
        at gui.GUI.lambda$null$0(GUI.java:157)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
PS C:\Users\Surbhit> java -jar Novel-Grabber.jar
Fetching latest selector JSON from GitHub...
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=503, URL=https://comrademao.com/novel/rebirth-of-the-devouring-emperor/
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
        at grabber.HostSettings.getChapterList(HostSettings.java:141)
        at grabber.Novel.getChapterList(Novel.java:71)
        at gui.GUI.lambda$null$0(GUI.java:156)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
        at grabber.Metadata.getTitle(Metadata.java:33)
        at grabber.Novel.getMetadata(Novel.java:105)
        at gui.GUI.lambda$null$0(GUI.java:157)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
1111 [pool-2-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 81.0.4044.138 (since Google Chrome 81 is installed in your machine)
1193 [pool-2-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\Surbhit\.m2\repository\webdriver\chromedriver\win32\81.0.4044.138\chromedriver.exe
Starting ChromeDriver 81.0.4044.138 (8c6c7ba89cc9453625af54f11fd83179e23450fa-refs/branch-heads/4044@{#999}) on port 18757
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
May 15, 2020 9:02:19 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
[1589556745.576][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556745.682][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556745.786][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556746.304][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556746.413][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556746.517][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556746.621][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556746.727][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556746.832][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556746.936][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556747.040][SEVERE]: Timed out receiving message from renderer: 0.100
[1589556747.144][SEVERE]: Timed out receiving message from renderer: 0.100
Exception in thread "pool-2-thread-1" org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: /html/body/nav/label/ul/li[3]/a (tried for 30 second(s) with 500 milliseconds interval)
        at org.openqa.selenium.support.ui.WebDriverWait.timeoutException(WebDriverWait.java:95)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:272)
        at grabber.Driver.getChapterList(Driver.java:73)
        at grabber.Novel.getChapterList(Novel.java:67)
        at gui.GUI.lambda$null$0(GUI.java:156)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.NoSuchElementException: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/nav/label/ul/li[3]/a"}
  (Session info: headless chrome=81.0.4044.113)
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'DESKTOP-4IJM8PT', ip: '192.168.1.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_221'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 81.0.4044.113, chrome: {chromedriverVersion: 81.0.4044.138 (8c6c7ba89cc9..., userDataDir: C:\Users\Surbhit\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:39370}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: d112528c4921f1433ff03c84cac5027c
*** Element info: {Using=xpath, value=/html/body/nav/label/ul/li[3]/a}
        at sun.reflect.GeneratedConstructorAccessor15.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
        at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
        at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
        at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
        at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
        at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:205)
        at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:201)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:249)
        ... 6 more

**Comment by Flameish** [comment]
Thanks for the error log! I was able to fix it, check out [v2.4.5](https://github.com/Flameish/Novel-Grabber/releases/tag/2.4.5).

**Comment by croooked01** [comment]
> Thanks for the error log! I was able to fix it, check out [v2.4.5](https://github.com/Flameish/Novel-Grabber/releases/tag/2.4.5).

Still doesn't work.Though it displays the novel info. now after using "check availability of novel" but after clicking grab chapters it displays following messages:
[INFO]Fetching novel info...
[INFO]Starting headerless browser...
[ERROR]Failed to getRebirth-of-the-Devouring-Emperor.jpg
[INFO]Starting headerless browser...
[ERROR]Unable to parse remote response: Unknown error

**Comment by Flameish** [comment]
The first error is normal, I haven't quite figured out how to save images with Selenium(headless) yet. You need to manually change the cover image if you want it.

I don't get the 2nd error and it downloads the chapters just fine for me. Please post your console log again.
