### ISSUE TITLE
Try to download on multiple sites either wont or will start stop[BUG]

### ISSUE THREAD

**Issue by Killo1988** [Flameish/Novel-Grabber#312]
When I try to download now after I had to get new hard drive its now just will start the download then stop. I know some websites are having issues due to cloudflare, but i have tried multiple sites of the same book.
**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/88687686/139597544-dfd44245-2bd7-424e-8a9c-65d0f266a6ab.png)

**Platform**
Latest Windows 10 Latest Java

**Logs**
[2021-10-31T13:48:28] No settings file found.
[2021-10-31T13:48:28] No library file found.
[2021-10-31T13:49:16] Page not found! (404)
[2021-10-31T13:49:34] Bad request! (400)
[2021-10-31T13:49:34] java.lang.NullPointerException
	at grabber.sources.daonovel_com.getMetadata(daonovel_com.java:92)
	at grabber.Novel.check(Novel.java:84)
	at gui.GUI.lambda$null$0(GUI.java:270)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[2021-10-31T13:49:57] Forbidden! (403)
[2021-10-31T13:51:39] Host not supported: readlightnovel.me

**Additional context**

**Comment by Flameish** [comment]
Host not support is pretty self explanatory. Forbidden often means Cloudflare/Bot protection. In that Stacktrace you can see that it throws an error at getMetadata, this mostly means that the host changed something on their website which needs to be ajusted. Page not found is probably a typo in the url/chapter. 

I will take a look at DaoNovel.

**Comment by Flameish** [comment]
Also on the start / just stop issue (if the current screen is from that), then youre trying to download a novel with 0 chapters (bad programming that the button to start downloading is not greyed out)
