### ISSUE TITLE
https://www.webnovel.com [BUG]

### ISSUE THREAD

**Issue by stvwilling** [Flameish/Novel-Grabber#345]
cannot download books from website anymore

**Describe the bug**
error chapter container not found

**Logs**
[2022-04-12T18:35:53] Chapter container not found.
[2022-04-12T18:35:54] Chapter container not found.
[2022-04-12T18:35:54] java.lang.InterruptedException: Download stopped.
	at grabber.Novel.downloadChapters(Novel.java:115)
	at gui.GUI.lambda$null$2(GUI.java:351)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by Flameish** [comment]
See #343
