### ISSUE TITLE
Java 14 missing Java 8 package?  (java.lang.ClassNotFoundException: javax.activation.DataSource)

### ISSUE THREAD

**Issue by guneydoganer** [Flameish/Novel-Grabber#45]
When executing the jar on Arch Linux with :
java version "14.0.2" 2020-07-14
Java(TM) SE Runtime Environment (build 14.0.2+12-46)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

The packages I installed for Java were:
jdk 14.0.2 (aur)
jre 140.2 (aur)

I get the following error (and an empty window opens):

```

Exception in thread "pool-1-thread-1" java.lang.NoClassDefFoundError: javax/activation/DataSource
	at library.LibrarySystem.pollLibrary(LibrarySystem.java:21)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 4 more
```

I've managed to use the application before on Ubuntu/Deb based systems, but no luck on Arch Linux. I'm guessing it is becausing I'm missing a package and online searching (Google/StackOverflow) leads me to believe the missing package was present in Java 8, but was removed in later versions.

**Comment by guneydoganer** [comment]
Okay, I've managed to get it working. I probably should've added some extra information in my original post.
I'm making use of the Sway window manager on Wayland and I've added the following two environment variables:

```
 _JAVA_AWT_WM_NONREPARENTING=1
 NO_AT_BRIDGE=1
```

After rebooting, I still get the error, but the window that opens up is not empty anymore and shows the application itself.
I've also tried opening the jar with java 8 by using:

`archlinux-java set java-8-jre `

and the application managed to open without any errors and it confirmed my suspicion that something is missing in newer versions of Java (which used to be present in Java 8). I don't know how worthwhile it is to look into this issue, but as far as my original issue is concerned, please feel free to close this ticket :).
