### ISSUE TITLE
Novel-Grabber not working at all

### ISSUE THREAD

**Issue by mp3096** [Flameish/Novel-Grabber#66]
C:\Users\XXXX\Desktop>java -jar Novel-Grabber.jar
[CONFIG]Fetching latest selector JSON...
[CONFIG-ERROR]Could not fetch selectors from: https://raw.githubusercontent.com/Flameish/Novel-Grabber/master/src/main/resources/siteSelector.json
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://raw.githubusercontent.com/Flameish/Novel-Grabber/master/src/main/resources/siteSelector.json

In recent update i think u removed selector file from github is that why its happening? yesterday it was working fine

**Comment by mp3096** [comment]
https://prnt.sc/vjp7yb
commit a531828
u removed sites elector file maybe thats why?

**Comment by Flameish** [comment]
I always forget about that file breaking everything. My apologizes.
The new version will be released in a few hours. At least everyone will get the notice to download the new NG-Updater.

**Comment by Flameish** [comment]
New version: [Novel-Grabber.zip](https://dl.dropboxusercontent.com/s/kjdfl0xnt4xq9y4/Novel-Grabber.zip)

**Comment by Xerephy** [comment]
Why can't I download from WW? I got error[Null] every time I attempt to download from WW.

**Comment by Flameish** [comment]
It seems like WW is using Clouflare and sometimes it blocks the requests. I'll see what I can do about it.

**Comment by Flameish** [comment]
I've added headless grabbing to be used optionally for Wuxiaworld in the Source Settings.

**Comment by Xerephy** [comment]
When I check the Source Settings, I can only see the "Novelupdates" Tab. Did I do something wrong?

**Comment by Flameish** [comment]
The updater should download the new version. Maybe try deleting Novel-Graber.jar inside the bin folder.

**Comment by Xerephy** [comment]
Thank you for the advice, I'm now able to see the WW Source Settings but I still get Error[null]. Thank you in advance!

**Comment by Flameish** [comment]
Okay I need some more info then. Can you post the link and the output of the console when you start Novel-Grabber.jar (not the launcher) from a terminal?

**Comment by joecheung1** [comment]
Help, the program stops after it ask to me to choose what browser to emulate.  Here is the output of the console window:

PS I:\Novel-Grabber\bin> java -jar Novel-Grabber.jar
java.lang.NullPointerException
        at system.data.Settings.setPassword(Settings.java:173)
        at system.data.Settings.load(Settings.java:58)
        at system.data.Settings.getInstance(Settings.java:44)
        at system.notifications.EmailNotification.<init>(EmailNotification.java:25)
        at system.library.LibrarySystem.<init>(LibrarySystem.java:27)
        at system.init.processParams(init.java:34)
        at system.init.main(init.java:25)
[ERROR]Could not establish connection to SMTP Server. Check email settings.
Working...
java.lang.NullPointerException
        at java.util.Hashtable.put(Unknown Source)
        at java.util.Properties.setProperty(Unknown Source)
        at system.data.Settings.save(Settings.java:84)
        at gui.GUI.createUIComponents(GUI.java:1374)
        at gui.GUI.$$$setupUI$$$(GUI.java)
        at gui.GUI.<init>(GUI.java:45)
        at system.init.lambda$startGUI$0(init.java:61)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Working...

**Comment by Flameish** [comment]
I think this might have something to do with your settings.ini. Does your folder structure look like this:
NG/
bin/
library.json
manifest.json
NG-Launcher.jar
settings.ini

Maybe try to remove everything except NG-Launcher and let it download everything again.

**Comment by joecheung1** [comment]
Yes, that worked!!!  Thanks for your awesome program.
